name: Shared deployment

on:
  workflow_call:

jobs:
  deploy-dev:
    strategy:
      matrix:
        environment: [development, development2]
    uses: yevhenkainaraideals/github-pipeline-templates-public/.github/workflows/deploy.yml@main
    with:
      environment: ${{ matrix.environment }}

  deploy-stage:
    needs: deploy-dev
    strategy:
      matrix:
          environment: [staging, staging2]
    uses: yevhenkainaraideals/github-pipeline-templates-public/.github/workflows/deploy.yml@main
    with:
      environment: ${{ matrix.environment }}

  deploy-production:
    needs: deploy-stage
    uses: yevhenkainaraideals/github-pipeline-templates-public/.github/workflows/deploy.yml@main
    with:
      environment: production

