name: Shared deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy-dev:
    uses: yevhenkainaraideals/github-pipeline-templates-public/.github/workflows/deploy.yml@main
    with:
      environment: development

  deploy-stage:
    needs: deploy-dev
    uses: yevhenkainaraideals/github-pipeline-templates-public/.github/workflows/deploy.yml@main
    with:
      environment: staging

  deploy-production:
    needs: deploy-stage
    uses: yevhenkainaraideals/github-pipeline-templates-public/.github/workflows/deploy.yml@main
    with:
      environment: production

